name: user-gaze-track
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.1
  - flask=3.1.1
  - flask-sqlalchemy=3.1.1
  - flasgger=0.9.7.1
  - numpy=1.26.4
  - pip
  - pip:
    - ttkbootstrap==1.10.1
    - cryptography==46.0.2